"""initial migration

Revision ID: 177c29dc909a
Revises: 
Create Date: 2021-08-07 13:31:51.073723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177c29dc909a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('hero',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('comics_appeared_in', sa.String(length=300), nullable=True),
    sa.Column('super_power', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('owner_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    op.drop_table('user')
    # ### end Alembic commands ###
