"""empty message

Revision ID: 244d67a4bad3
Revises: 177c29dc909a
Create Date: 2021-08-07 13:40:13.706476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244d67a4bad3'
down_revision = '177c29dc909a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
