"""empty message

Revision ID: d4bdd4ef4d52
Revises: a64ff0053869
Create Date: 2021-08-08 22:35:47.524786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bdd4ef4d52'
down_revision = 'a64ff0053869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('alter_ego', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'alter_ego')
    # ### end Alembic commands ###
